/// Generated by AssetsRefGenerator on 2022/10/19
class Res {
  static const String p01 = "assets/images/background/p01.jpg";
  static const String p02 = "assets/images/background/p02.jpg";
  static const String p03 = "assets/images/background/p03.jpg";
  static const String p04 = "assets/images/background/p04.jpg";
  static const String p05 = "assets/images/background/p05.jpg";
  static const String p11 = "assets/images/background/p11.png";
  static const String p12 = "assets/images/background/p12.png";
  static const String p21 = "assets/images/background/p21.png";
  static const String p22 = "assets/images/background/p22.png";
  static const String p23 = "assets/images/background/p23.png";
  static const String p24 = "assets/images/background/p24.png";
  static const String p25 = "assets/images/background/p25.png";
  static const String p26 = "assets/images/background/p26.png";
  static const String p27 = "assets/images/background/p27.png";
}
